### ISSUE TITLE
Src Document.

### ISSUE THREAD

**Issue by krishna-iamneo** [krishna-iamneo/Job-Board-2#39]
Prepare the src documentation, required for project.

**Comment by nagasaineo** [comment]
yeah I will check it out.

**Comment by krishna-iamneo** [comment]
Reach out @shivam-neo for any doubts.

**Comment by nagasaineo** [comment]
ok I am already working on it

**Comment by nagasaineo** [comment]
[Software Requirements Specification(SRS).docx](https://github.com/krishna-iamneo/Job-Board-2/files/14831791/Software.Requirements.Specification.SRS.docx)

**Comment by krishna-iamneo** [comment]
@shivam-neo check the file and update

**Comment by nagasaineo** [comment]
check SRS document once @shivam-neo

**Comment by shivam-neo** [comment]
Done good to go
