### ISSUE TITLE
Uml diagram

### ISSUE THREAD

**Issue by krishna-iamneo** [krishna-iamneo/Job-Board-2#40]
Draw uml diagrams for the project.
use case diagram
activity diagram

refer requirements sheet.

**Comment by bharath-neo** [comment]
Yeah, Completed just check it and let me know if any changes is required.

**Comment by bharath-neo** [comment]
[JBUML.docx](https://github.com/krishna-iamneo/Job-Board-2/files/14831635/JBUML.docx)

**Comment by krishna-iamneo** [comment]
It is good, but do it in word document.

**Comment by krishna-iamneo** [comment]
@bharath-neo Use Draw.io tool do the uml diagrams

**Comment by bharath-neo** [comment]
Just check this out @krishna-iamneo 
[JBUMLrectified.docx](https://github.com/krishna-iamneo/Job-Board-2/files/14832644/JBUMLrectified.docx)
.

**Comment by krishna-iamneo** [comment]
yeah, this is ok

**Comment by bharath-neo** [comment]
@krishna-iamneo  just check out this one.
[JBUMLrectified.docx](https://github.com/krishna-iamneo/Job-Board-2/files/14849918/JBUMLrectified.docx)
